name: Release and publish on tag
on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'
    branches: [master]

jobs:
  build:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16 ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn build
      
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "extension/jiffyReader-chrome.zip, extension/jiffyReader-firefox.xpi, extension/jiffyReader-opera.crx, extension/jiffyReader-bookmarklet.html"
          token: ${{ secrets.GITHUB_TOKEN }}
